[client]
showErrorDetails = false
showSidebarNavigation = false

[logger]
level = "error"

[server]
headless = true
port = 8501

[theme]
base = "dark"
primaryColor = "#62D6C8"
backgroundColor = "#08131F"
secondaryBackgroundColor = "#10243A"
textColor = "#E8F0FA"
font = "sans serif"